### ISSUE TITLE
ImportError: No module named PyCommand

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#108]
After accepting latest changes, commands are found to be not working due to the following error:-

(ENV)[mangirish@MangoLap client]$ cm vm refresh
Traceback (most recent call last):
  File "/home/mangirish/ENV/bin/cm", line 9, in <module>
    load_entry_point('cloudmesh-client==0.7.3', 'console_scripts', 'cm')()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/cm.py", line 10, in <module>
    from .plugins import *
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins/__init__.py", line 29, in <module>
    from cloudmesh_client.shell.plugins.PyCommand import PyCommand
ImportError: No module named PyCommand

**Comment by vaglomangirish** [comment]
Delivered a minor change to cloudmesh_client/shell/plugins/__init__.py to fix the issue.
