### ISSUE TITLE
ImportError: No module named httpsig.requests_auth

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#118]
After accepting latest code, I hit this issue:-

$ cm launcher suspend
Traceback (most recent call last):
  File "/home/mangirish/ENV/bin/cm", line 9, in <module>
    load_entry_point('cloudmesh-client==0.7.7', 'console_scripts', 'cm')()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client-0.7.7-py2.7.egg/cloudmesh_client/shell/cm.py", line 34, in <module>
    from .plugins import *
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client-0.7.7-py2.7.egg/cloudmesh_client/shell/plugins/__init__.py", line 3, in <module>
    from cloudmesh_client.shell.plugins.CometCommand import CometCommand
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client-0.7.7-py2.7.egg/cloudmesh_client/shell/plugins/CometCommand.py", line 3, in <module>
    from cloudmesh_client.comet.comet import Comet
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client-0.7.7-py2.7.egg/cloudmesh_client/comet/comet.py", line 10, in <module>
    from httpsig.requests_auth import HTTPSignatureAuth
ImportError: No module named httpsig.requests_auth

**Comment by vaglomangirish** [comment]
Added httpsig to requirements.txt to fix the issue
