### ISSUE TITLE
doc: rtd failed

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#134]
Running Sphinx v1.3.4
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudmesh-client/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudmesh-client/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudmesh-client/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudmesh-client/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudmesh-client/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 16, in <module>
    from cloudmesh_client.version import __version__
ImportError: No module named cloudmesh_client.version

Exception occurred:
  File "conf.py", line 16, in <module>
    from cloudmesh_client.version import __version__
ImportError: No module named cloudmesh_client.version
The full traceback has been saved in /tmp/sphinx-err-twTXMq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by badi** [comment]
You may need to tell RTD to install the client via the rtd project admin page. Lets look at it tomorrow.
