### ISSUE TITLE
`make doc` breaks `cm man`

### ISSUE THREAD

**Issue by badi** [cloudmesh/client#152]
I noticed this while working on the dockerfile. After installing client, this works:

```
$ cm man
```

But this breaks:
```
$ pip install -r requirements-doc.txt
$ make doc
$ cm man
```

@laszewsk For the purposes of dockerfile, I'm not going to investigate much further, but here is the full traceback for reference:

```
Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for cloudmesh-client==2.1.0
cm man > docs/source/man/man.rst
Traceback (most recent call last):
  File "/usr/local/bin/cm", line 9, in <module>
    load_entry_point('cloudmesh-client==2.1.0', 'console_scripts', 'cm')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/shell/cm.py", line 35, in <module>
    from cloudmesh_client.cloud.default import Default
  File "/usr/local/lib/python2.7/dist-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/cloud/default.py", line 5, in <module>
    from cloudmesh_client.db.CloudmeshDatabase import CloudmeshDatabase
  File "/usr/local/lib/python2.7/dist-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/db/CloudmeshDatabase.py", line 16, in <module>
    from cloudmesh_client.cloud.iaas.CloudProvider import CloudProvider
  File "/usr/local/lib/python2.7/dist-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/cloud/iaas/CloudProvider.py", line 2, in <module>
    from cloudmesh_client.cloud.iaas.provider.openstack.CloudProviderOpenstackAPI import \
  File "/usr/local/lib/python2.7/dist-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/cloud/iaas/provider/openstack/CloudProviderOpenstackAPI.py", line 11, in <module>
    from novaclient import client
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 38, in <module>
    from oslo_utils import netutils
  File "/usr/local/lib/python2.7/dist-packages/oslo_utils/netutils.py", line 281, in <module>
    class _ModifiedSplitResult(parse.SplitResult):
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'SplitResult'
make: *** [man] Error 1
The command '/bin/sh -c make doc' returned a non-zero code: 2
```

**Comment by laszewsk** [comment]
make sure api doc shows up after make doc

**Comment by laszewsk** [comment]
make doc works now in python 2.7.11 and 3.5
