### ISSUE TITLE
command: secgroup

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#153]
**branch**: category

deleting security groups does not work if the group name is not unique

cm secgroup delete  test-group --tenant=fg491
ERROR: 

Traceback (most recent call last):
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client-2.1.0-py2.7.egg/cloudmesh_client/cloud/secgroup.py", line 352, in delete_secgroup
    sec_group = cloud_provider.security_groups.find(name=label)
  File "/Users/big/ENV/lib/python2.7/site-packages/novaclient/base.py", line 339, in find
    raise exceptions.NoUniqueMatch
NoUniqueMatch

ERROR: Security Group [test-group, kilo, fg491] could not be deleted

**Comment by gouravshenoy** [comment]
This issue has been fixed. Now security groups with unique names are deleted on any cloud. Closing this issue now.
