### ISSUE TITLE
command: delete vms with same name

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#155]
when a vm with the same name exists it gets an exception

expected behavious is to delete them all or if you do a -ask flag it asks for each deletion.

cm vm delete testvm
Traceback (most recent call last):
  File "/Users/ /ENV/lib/python2.7/site-packages/cloudmesh_client-2.1.2-py2.7.egg/cloudmesh_client/shell/plugins/VmCommand.py", line 472, in do_vm
    Vm.delete(cloud=cloud, servers=servers)
  File "/Users/ /ENV/lib/python2.7/site-packages/cloudmesh_client-2.1.2-py2.7.egg/cloudmesh_client/cloud/vm.py", line 125, in delete
    cloud_provider.delete_vm(server)
  File "/Users /ENV/lib/python2.7/site-packages/cloudmesh_client-2.1.2-py2.7.egg/cloudmesh_client/cloud/iaas/provider/openstack/CloudProviderOpenstackAPI.py", line 343, in delete_vm
    server = self.provider.servers.find(name=name)
  File "/Users/ /ENV/lib/python2.7/site-packages/novaclient/base.py", line 339, in find
    raise exceptions.NoUniqueMatch
NoUniqueMatch

**Comment by laszewsk** [comment]
implemented by gregor
