### ISSUE TITLE
image refresh for chameleon failed

### ISSUE THREAD

**Issue by badi** [cloudmesh/client#247]
##### ISSUE TYPE

 - Bug Report

##### CM VERSION
```
$ cm version
+------------------+---------+
| name             | version |
+------------------+---------+
| python           | 2.7.12  |
| pip              | 8.1.2   |
| cloudmesh_client | 4.3.7   |
| git hash         | d766b41 |
+------------------+---------+
You are running a supported version of python: 2.7.12
You are running a supported version of pip: 8.1.2
```

##### CM INFO

```
[nix-shell:~/github.com/cloudmesh/client]$ cm info
+-------------+-------------------------+
| Attribute   | Value                   |
+-------------+-------------------------+
| cloud       | chameleon               |
| key         | badi                    |
| user        | badi                    |
| vm          |                         |
| group       | default                 |
| secgroup    | badi-default            |
| counter     | 1                       |
| image       | Ubuntu-Server-14.04-LTS |
| flavor      | m1.small                |
| refresh     | None                    |
| debug       | True                    |
| interactive | None                    |
| purge       | None                    |
+-------------+-------------------------+

```

##### STEPS TO REPRODUCE

```
$ cm image refresh --cloud=chameleon
/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/novaclient/client.py:860: UserWarning: Only VERSION, USERNAME, PASSWORD, PROJECT_ID and AUTH_URL arguments can be specified as positional arguments. All other variables should be keyword arguments. Note that this will become an error in Ocata.
  warnings.warn("Only VERSION, USERNAME, PASSWORD, PROJECT_ID and "
__init__() got multiple values for keyword argument 'username'
Traceback (most recent call last):
  File "/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/cloudmesh_client/cloud/iaas/CloudProvider.py", line 33, in __init__
    flat=flat)
  File "/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/cloudmesh_client/cloud/iaas/provider/openstack/CloudProviderOpenstackAPI.py", line 59, in __init__
    self.initialize(cloud_name, cloud_details)
  File "/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/cloudmesh_client/cloud/iaas/provider/openstack/CloudProviderOpenstackAPI.py", line 273, in initialize
    cert)
  File "/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/novaclient/client.py", line 870, in Client
    *args, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'username'

ERROR: Problem with secgroup
Traceback (most recent call last):
  File "/home/badi/github.com/cloudmesh/client/venv/lib/python2.7/site-packages/cloudmesh_client/db/CloudmeshDatabase.py", line 935, in refresh
    provider = CloudProvider(name).provider
AttributeError: 'CloudProvider' object has no attribute 'provider'
ERROR: Refresh image for cloud chameleon. failed.
None

```

**Comment by fugangwang** [comment]
This was due to the identity api version change. Changing the v2.0 to v3 on the auth_url should fix this.
