### ISSUE TITLE
cm 4.5 update issue

### ISSUE THREAD

**Issue by tonythomascn** [cloudmesh/client#257]
##### ISSUE TYPE

 - Bug Report

Searching for keystoneauth1==2.18.0
Reading https://pypi.python.org/simple/keystoneauth1/
Downloading https://pypi.python.org/packages/d7/f5/d6e5d18d46ac30369f334eda6b751096c6c5e85688a3b388ff4622f53e9a/keystoneauth1-2.18.0.tar.gz#md5=d24c08bc7d59081adce160444ebc6993
Best match: keystoneauth1 2.18.0
Processing keystoneauth1-2.18.0.tar.gz
Writing /var/folders/8z/xx21qgmx1pv1pjzk1t4llj1m0000gn/T/easy_install-dog4hY/keystoneauth1-2.18.0/setup.cfg
Running keystoneauth1-2.18.0/setup.py -q bdist_egg --dist-dir /var/folders/8z/xx21qgmx1pv1pjzk1t4llj1m0000gn/T/easy_install-dog4hY/keystoneauth1-2.18.0/egg-dist-tmp-ud76Wb
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/tony/pyenv/cloudmesh/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/tony/pyenv/cloudmesh/lib/python2.7/site-packages/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/Users/tony/pyenv/cloudmesh/lib/python2.7/site-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/Users/tony/pyenv/cloudmesh/lib/python2.7/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /private/var/folders/8z/xx21qgmx1pv1pjzk1t4llj1m0000gn/T/easy_install-dog4hY/keystoneauth1-2.18.0/setup.cfg: TypeError: dist must be a Distribution instance

##### CM VERSION

```
cm 4.5
```

##### CM INFO

```

```

##### SUMMARY

I was trying to update from cm 4.4 to 4.5. I have had virtualenv activated.

##### STEPS TO REPRODUCE

```
./install
```

##### ACTUAL RESULTS

```

```

**Comment by fugangwang** [comment]
'pip install .' is the recommended way for the client installation. Changed in commit 90c13aa
