### ISSUE TITLE
cm register check

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#37]
C:\Users\erika> cm register check
ERROR: executing command 'register check'
======================================================================
could not find file C:\Users\erika\.cloudmesh\cloudmesh.yaml in ['.', '~\\.cloudmesh']
======================================================================
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cloudmesh_client\shell\cm.py", line 390, in main
    cmd.onecmd(user_cmd)
  File "C:\Python27\lib\cmd.py", line 221, in onecmd
    return func(arg)
  File "C:\Python27\lib\site-packages\cloudmesh_client\shell\command.py", line 39, in new
    func(instance, args, arguments)
  File "C:\Python27\lib\site-packages\cloudmesh_client\shell\plugins\RegisterCommand.py", line 165, in do_register
    CloudRegister.check_yaml_for_completeness(filename)
  File "C:\Python27\lib\site-packages\cloudmesh_client\cloud\register.py", line 90, in check_yaml_for_completeness
    config = ConfigDict(filename)
  File "C:\Python27\lib\site-packages\cloudmesh_client\common\ConfigDict.py", line 116, in __init__
    .format(filename, self.load_order))
Exception: could not find file C:\Users\erika\.cloudmesh\cloudmesh.yaml in ['.', '~\\.cloudmesh']

**Comment by ehdsouza** [comment]
File names were appended twice, corrected the code..

C:\Users\erika> cm register check
Checking the yaml file
ERROR: The file has 14 values to be fixed

  firstname: TBD
  lastname: TBD
  email: TBD
  username: TBD
  flavor: TBD
  image: TBD
  EC2_ACCESS_KEY: TBD
  EC2_SECRET_KEY: TBD
  keyname: TBD
  userid: TBD
  managementcertfile: TBD
  servicecertfile: TBD
  subscriptionid: TBD
  thumbprint: TBD
