### ISSUE TITLE
ConfigDict: path issue

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#41]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/cloudmesh/client/github/cloudmesh/client/tests/test_configdict.py", line 35, in test_001_read
    verbose=True)
  File "/home/travis/build/cloudmesh/client/github/cloudmesh/client/cloudmesh_client/common/ConfigDict.py", line 105, in __init__
    name = Config.path_expand(os.path.join(path, filename))
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/posixpath.py", line 68, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'list' object has no attribute 'endswith'

**Comment by ehdsouza** [comment]
Corrected the code to take in list during function call, https://github.com/cloudmesh/client/commit/ef5062db8a6256a88062b9a15b1af189b237f761
