### ISSUE TITLE
'KEY' object is not iterable

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#53]
I hit this issue when getting the cm key default command working.

(ENV)[mangirish@MangoLap client]$ cm key default
{'--all': False,
 '--dir': '~/.ssh',
 '--format': 'table',
 '--git': False,
 '--help': False,
 '--name': None,
 '--select': False,
 '--source': 'db',
 '--ssh': False,
 '--username': 'none',
 '-f': False,
 '-h': False,
 'FILENAME': None,
 'KEYNAME': None,
 'NAME': None,
 'add': False,
 'default': True,
 'delete': False,
 'get': False,
 'list': False}
default
DEFAULT KEY: <cloudmesh_client.db.model.KEY object at 0x4ade7d0>
Traceback (most recent call last):
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins/KeyCommand.py", line 356, in do_key
    default_dict = sshdb.object_to_dict(default_key)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/db/SSHKeyDBManager.py", line 148, in object_to_dict
    return self.db.object_to_dict(obj)
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/db/CloudmeshDatabase.py", line 125, in object_to_dict
    for u in obj:
TypeError: 'KEY' object is not iterable

'KEY' object is not iterable
ERROR: Default key retrieval failed.

Apparently, when you try applying object_to_dict on KEY, it reports not iterable.

This requires further investigation.

**Comment by laszewsk** [comment]
if object is none you can not itterate

**Comment by laszewsk** [comment]
what is status of this?
