### ISSUE TITLE
command: key list 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#95]
ERROR: executing command 'key list'
======================================================================
local variable 'username' referenced before assignment
======================================================================
Traceback (most recent call last):
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/cm.py", line 418, in main
    cmd.onecmd(user_cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/command.py", line 39, in new
    func(instance, args, arguments)
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins/KeyCommand.py", line 214, in do_key
    Console.error("Problem listing keys from database for user: " + username)
UnboundLocalError: local variable 'username' referenced before assignment

**Comment by vaglomangirish** [comment]
Removed the unresolved reference to username.
