### ISSUE TITLE
command: vm list 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#96]
Traceback (most recent call last):
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/cloud/vm.py", line 18, in get_cloud_provider
    return CloudProviderOpenstack(name, cloud_details)
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/cloud/iaas/CloudProviderOpenstack.py", line 10, in __init__
    self.initialize(cloud_name, cloud_details)
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/cloud/iaas/CloudProviderOpenstack.py", line 18, in initialize
    self.nova = client.Client(version, credentials["OS_USERNAME"], credentials["OS_PASSWORD"],
TypeError: string indices must be integers, not str

string indices must be integers, not str
Traceback (most recent call last):
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins/VmCommand.py", line 386, in do_vm
    list_vms_on_cloud(cloud, group, _format)
  File "/Users/big/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins/VmCommand.py", line 162, in list_vms_on_cloud
    servers = cloud_provider.list()
AttributeError: 'NoneType' object has no attribute 'list'

'NoneType' object has no attribute 'list'
ERROR: Problem listing instances on cloud india

**Comment by vaglomangirish** [comment]
Fix delivered for this issue, verified by Erika...
VM list implementation has been changed to list VMs from DB.
